server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: nodus

  forward-headers-strategy: framework

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/nodus}
      auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:false}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

jwt:
  secret: "dev-secret-key-dev-secret-key-32-bytes!!"
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 1209600
