spring:
  application:
    name: nodus

  forward-headers-strategy: framework

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/nodus}
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

jwt:
  secret: "dev-secret-key-dev-secret-key-32-bytes!!"
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 1209600

google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}